#ifndef DEBRIS_CONFIG_H
#define DEBRIS_CONFIG_H

#include <stddef.h>
#include <stdint.h>

#define DF_DEV_ID 0
#define DF_PIPE_ID 0
#define DF_DETECT_CHN 2

#define DF_WIDTH 640
#define DF_HEIGHT 360
#define DF_MAX_WIDTH 960
#define DF_MAX_HEIGHT 540

#define DF_WARMUP_FRAMES 90ULL
#define DF_BACKGROUND_DIFF_THRESHOLD 20
#define DF_FRAME_DIFF_THRESHOLD 12
#define DF_MOTION_LOG_INTERVAL 10ULL
#define DF_BACKGROUND_UPDATE_DIVISOR 32
#define DF_SELECTIVE_BG_LEARN_DIFF_THRESHOLD 20
#define DF_SELECTIVE_FRAME_STABLE_THRESHOLD 8
#define DF_BACKGROUND_FRACTION_BITS 8
#define DF_BACKGROUND_SCALE (1 << DF_BACKGROUND_FRACTION_BITS)
#define DF_BRIGHTNESS_COMPENSATION_LIMIT 20

#define DF_GULLY_MOTION_THRESHOLD 0.04
#define DF_STATIC_MOTION_THRESHOLD 0.05
#define DF_CAMERA_SHAKE_STATIC_BG_THRESHOLD 0.03
#define DF_CAMERA_SHAKE_STATIC_FRAME_THRESHOLD 0.02

#define DF_REBASE_GLOBAL_BG_THRESHOLD 0.10
#define DF_REBASE_GULLY_BG_THRESHOLD 0.08
#define DF_REBASE_STATIC_BG_THRESHOLD 0.05
#define DF_REBASE_GLOBAL_FRAME_STABLE_THRESHOLD 0.01
#define DF_REBASE_GULLY_FRAME_STABLE_THRESHOLD 0.01
#define DF_REBASE_STATIC_FRAME_STABLE_THRESHOLD 0.01
#define DF_REBASE_STABLE_FRAMES 30ULL
#define DF_REBASE_HOLD_FRAMES 30ULL

#define DF_EVENT_ENTER_GULLY_BG_THRESHOLD 0.04
#define DF_EVENT_ENTER_GULLY_FRAME_THRESHOLD 0.02
#define DF_EVENT_HOLD_GULLY_BG_THRESHOLD 0.03
#define DF_EVENT_HOLD_GULLY_FRAME_THRESHOLD 0.008
#define DF_EVENT_STATIC_BG_VETO_THRESHOLD 0.05
#define DF_EVENT_STATIC_FRAME_VETO_THRESHOLD 0.02
#define DF_EVENT_CONFIRM_FRAMES 8ULL
#define DF_EVENT_MISS_TO_RECOVER_FRAMES 5ULL
#define DF_EVENT_RECOVERY_FRAMES 20ULL

#define DF_BLOB_MIN_AREA 120
#define DF_TRACK_MIN_BLOB_AREA 300
#define DF_TRACK_MAX_MATCH_DISTANCE_PX 160.0
#define DF_TRACK_MAX_AREA_RATIO 5.0
#define DF_TRACK_DOMINANT_REPLACEMENT_AREA_FACTOR 4.0
#define DF_TRACK_MAX_MISSED_FRAMES 6ULL
#define DF_TRACK_DIRECTION_WINDOW_FRAMES 5ULL
#define DF_TRACK_DIRECTION_MIN_DISPLACEMENT_PX 6.0
#define DF_FAST_CAMERA_SHAKE_STATIC_FRAME_THRESHOLD 0.05

#define DF_EVENT_SUMMARY_UPDATE_INTERVAL_SECONDS 1.0
#define DF_EVENT_SNAPSHOT_INTERVAL_SECONDS 30.0
#define DF_EVENT_CLOSE_GRACE_SECONDS 3.0
#define DF_OUTSIDE_GULLY_CAMERA_MOTION_THRESHOLD 0.03
#define DF_CAMERA_DISTURBANCE_HOLD_FRAMES 30ULL
#define DF_POST_SHAKE_REBASE_GLOBAL_BG_THRESHOLD 0.10
#define DF_POST_SHAKE_REBASE_OUTSIDE_BG_THRESHOLD 0.08
#define DF_POST_SHAKE_STABLE_FRAME_THRESHOLD 0.01
#define DF_POST_SHAKE_REBASE_STABLE_FRAMES 30ULL
#define DF_POST_SHAKE_GUARD_MAX_FRAMES 90ULL

#define DF_SNAPSHOT_RING_SLOTS 8ULL
#define DF_MONITOR_MESSAGE_QUEUE_CAPACITY 64U
#define DF_SNAPSHOT_PACKAGE_QUEUE_CAPACITY 8U
#define DF_EVENT_DIRECTION_VOTE_MIN_SPEED_PX_S 15.0
#define DF_COARSE_DIRECTION_COUNT 10


/* UART2 / LoRa transparent-UART transport defaults. */
#define DF_UART2_DEFAULT_DEVICE "/dev/ttyS2"
#define DF_UART2_DEFAULT_BAUD 115200
#define DF_UART2_DEFAULT_DEVICE_ID 1U

#define DF_GULLY_POINT_COUNT 4U
#define DF_STATIC_POINT_COUNT 4U

#endif
